# Generated by Django 5.2.7 on 2025-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisis', '0006_accident_police_accident_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='ambphone',
            field=models.CharField(max_length=100, verbose_name='ambphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='emergency'),
        ),
    ]
